# Generated by Django 3.0.3 on 2020-05-09 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
